import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import PrimaryLinkButton from "~/component/PrimaryLinkButton";


function HeroBanner() {
  return <section className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-3 mt-10 mb-10 sm:mt-24 ">
    <div className="flex flex-col gap-4">
      <h1 className="text-5xl font-extrabold tracking-tight text-dark dark:text-white sm:text-[5rem]">
        Generate <span className="text-[hsl(280,100%,70%)]">Icons</span> with a click of a button
      </h1>
      <p className="text-2xl">Use AI to generate icons in seconds instead of paying a designer and waiting for them to create them for you</p>
      <PrimaryLinkButton href="/generate" className="self-start">Generate your Icons</PrimaryLinkButton>
    </div>
    <div className="flex justify-center items-center">
      <Image
        src="/heroImage-min.png"
        alt="an image of a bunch of nice looking icons"
        width="200"
        height="300"
      />
      <Image
        src="/heroImage2-min.png"
        alt="an image of a bunch of nice looking icons"
        width="200"
        height="300"
      />
    </div>
  </section>
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;

